export interface Universite {
  id: number
  slug: string
  name: string
  logo: string
  city: string
  citySlug: string
  type: 'Devlet' | 'Vakıf'
  foundedYear: number
  studentCount: number
  website: string
  shortDescription: string
  description: string
  rating?: number
}

export const universiteler: Universite[] = [
  {
    id: 1,
    slug: 'bogazici-universitesi',
    name: 'Boğaziçi Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Bogazici_University_Logo.png/240px-Bogazici_University_Logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Devlet',
    foundedYear: 1863,
    studentCount: 15000,
    website: 'https://bogazici.edu.tr',
    shortDescription: 'Türkiye\'nin en prestijli üniversitelerinden biri',
    description: 'Boğaziçi Üniversitesi, 1863 yılında Robert Koleji olarak kurulmuş, Türkiye\'nin en köklü ve prestijli yükseköğretim kurumlarından biridir. İngilizce eğitim veren üniversite, akademik başarıları ve uluslararası tanınırlığı ile öne çıkar. Boğaz manzaralı kampüsü ile de meşhurdur.',
    rating: 4.8,
  },
  {
    id: 2,
    slug: 'odtu',
    name: 'Orta Doğu Teknik Üniversitesi (ODTÜ)',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/METU_Logo.png/240px-METU_Logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Devlet',
    foundedYear: 1956,
    studentCount: 27000,
    website: 'https://metu.edu.tr',
    shortDescription: 'Mühendislik ve teknolojide öncü üniversite',
    description: 'ODTÜ, 1956 yılında kurulmuş ve özellikle mühendislik alanında Türkiye\'nin en güçlü üniversitelerinden biridir. İngilizce eğitim veren ODTÜ, geniş kampüsü, akademik özgürlüğü ve mezunlarının başarılarıyla tanınır. Ankara\'nın Çankaya ilçesinde bulunur.',
    rating: 4.7,
  },
  {
    id: 3,
    slug: 'itu',
    name: 'İstanbul Teknik Üniversitesi (İTÜ)',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Istanbul_Technical_University_logo.png/240px-Istanbul_Technical_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Devlet',
    foundedYear: 1773,
    studentCount: 39000,
    website: 'https://itu.edu.tr',
    shortDescription: 'Dünyanın en eski teknik üniversitelerinden',
    description: 'İTÜ, 1773 yılında kurulmuş dünyanın en eski teknik üniversitelerinden biridir. Mühendislik ve mimarlık alanlarında güçlü bir geleneğe sahiptir. Ayazağa ve Taşkışla kampüsleri ile İstanbul\'da 250 yılı aşkın bir tarihi vardır.',
    rating: 4.6,
  },
  {
    id: 4,
    slug: 'hacettepe',
    name: 'Hacettepe Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Hacettepe_University_logo.png/240px-Hacettepe_University_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Devlet',
    foundedYear: 1967,
    studentCount: 45000,
    website: 'https://hacettepe.edu.tr',
    shortDescription: 'Tıp fakültesiyle öne çıkan köklü üniversite',
    description: 'Hacettepe Üniversitesi, 1967 yılında kurulmuş olup özellikle tıp, sağlık bilimleri ve mühendislik alanlarında öne çıkar. Beytepe ve Sıhhiye kampüsleri ile Ankara\'nın en büyük üniversitelerinden biridir.',
    rating: 4.4,
  },
  {
    id: 5,
    slug: 'ankara-universitesi',
    name: 'Ankara Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Ankara_University_logo.png/240px-Ankara_University_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Devlet',
    foundedYear: 1946,
    studentCount: 65000,
    website: 'https://ankara.edu.tr',
    shortDescription: 'Cumhuriyetin ilk üniversitesi',
    description: 'Ankara Üniversitesi, 1946 yılında kurulmuş Cumhuriyet döneminin ilk üniversitesidir. Hukuk, siyasal bilgiler, veterinerlik ve ziraat fakülteleri ile tanınır. Türkiye\'nin akademik geleneğinin temellerini atan kurumlardan biridir.',
    rating: 4.3,
  },
  {
    id: 6,
    slug: 'istanbul-universitesi',
    name: 'İstanbul Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Istanbul_University_logo.png/240px-Istanbul_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Devlet',
    foundedYear: 1453,
    studentCount: 60000,
    website: 'https://istanbul.edu.tr',
    shortDescription: 'Türkiye\'nin en eski üniversitesi',
    description: 'İstanbul Üniversitesi, 1453 yılına dayanan tarihi ile Türkiye\'nin en eski üniversitesidir. Beyazıt\'taki tarihi ana binası ile bilinen üniversite, hukuk, tıp, edebiyat ve fen bilimleri alanlarında güçlüdür.',
    rating: 4.2,
  },
  {
    id: 7,
    slug: 'marmara',
    name: 'Marmara Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Marmara_University_logo.png/240px-Marmara_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Devlet',
    foundedYear: 1883,
    studentCount: 70000,
    website: 'https://marmara.edu.tr',
    shortDescription: 'İktisadi bilimlerde güçlü köklü üniversite',
    description: 'Marmara Üniversitesi, 1883\'te kurulmuş köklü bir üniversitedir. İktisat, işletme, siyasal bilgiler ve iletişim fakülteleri ile öne çıkar. İstanbul\'un farklı yerlerinde birden fazla kampüse sahiptir.',
    rating: 4.1,
  },
  {
    id: 8,
    slug: 'yildiz-teknik',
    name: 'Yıldız Teknik Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Yildiz_Technical_University_logo.png/240px-Yildiz_Technical_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Devlet',
    foundedYear: 1911,
    studentCount: 32000,
    website: 'https://yildiz.edu.tr',
    shortDescription: 'Mühendislikte güçlü teknik üniversite',
    description: 'YTÜ, 1911\'de kurulmuş, mühendislik ve mimarlık alanlarında güçlü bir teknik üniversitedir. Yıldız ve Davutpaşa kampüsleri ile İstanbul\'da eğitim veriyor.',
    rating: 4.2,
  },
  {
    id: 9,
    slug: 'ege',
    name: 'Ege Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Ege_University_logo.png/240px-Ege_University_logo.png',
    city: 'İzmir',
    citySlug: 'izmir',
    type: 'Devlet',
    foundedYear: 1955,
    studentCount: 55000,
    website: 'https://ege.edu.tr',
    shortDescription: 'İzmir\'in en köklü üniversitesi',
    description: 'Ege Üniversitesi, 1955\'te İzmir\'de kurulmuş büyük bir devlet üniversitesidir. Tıp, ziraat, mühendislik ve fen bilimleri alanlarında öne çıkar. Bornova\'daki geniş kampüsü ile bilinir.',
    rating: 4.3,
  },
  {
    id: 10,
    slug: 'dokuz-eylul',
    name: 'Dokuz Eylül Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Dokuz_Eylul_University_logo.png/240px-Dokuz_Eylul_University_logo.png',
    city: 'İzmir',
    citySlug: 'izmir',
    type: 'Devlet',
    foundedYear: 1982,
    studentCount: 65000,
    website: 'https://deu.edu.tr',
    shortDescription: 'İzmir\'in büyük devlet üniversitesi',
    description: 'Dokuz Eylül Üniversitesi, 1982\'de kurulmuş, İzmir\'in en büyük üniversitelerinden biridir. Tıp, hukuk, işletme ve mühendislik fakülteleri ile öne çıkar.',
    rating: 4.2,
  },
  {
    id: 11,
    slug: 'gazi',
    name: 'Gazi Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Gazi_University_logo.png/240px-Gazi_University_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Devlet',
    foundedYear: 1926,
    studentCount: 70000,
    website: 'https://gazi.edu.tr',
    shortDescription: 'Öğretmen yetiştirmede öncü',
    description: 'Gazi Üniversitesi, 1926\'da Atatürk tarafından "Gazi Eğitim Enstitüsü" olarak kurulmuştur. Türkiye\'nin öğretmen yetiştirmede en köklü kurumlarından biridir. Tıp ve mühendislik alanlarında da güçlüdür.',
    rating: 4.1,
  },
  {
    id: 12,
    slug: 'anadolu',
    name: 'Anadolu Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Anadolu_University_logo.png/240px-Anadolu_University_logo.png',
    city: 'Eskişehir',
    citySlug: 'eskisehir',
    type: 'Devlet',
    foundedYear: 1958,
    studentCount: 1200000,
    website: 'https://anadolu.edu.tr',
    shortDescription: 'Türkiye\'nin en büyük açık öğretim üniversitesi',
    description: 'Anadolu Üniversitesi, 1958\'de Eskişehir\'de kurulmuş olup Açık Öğretim Fakültesi ile Türkiye\'nin en büyük üniversitesidir. Yaklaşık 1.2 milyon öğrenciye eğitim vermektedir. İletişim ve iktisadi bilimler alanlarında da güçlüdür.',
    rating: 4.0,
  },
  {
    id: 13,
    slug: 'ktu',
    name: 'Karadeniz Teknik Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/KTU_logo.png/240px-KTU_logo.png',
    city: 'Trabzon',
    citySlug: 'trabzon',
    type: 'Devlet',
    foundedYear: 1955,
    studentCount: 60000,
    website: 'https://ktu.edu.tr',
    shortDescription: 'Karadeniz\'in köklü üniversitesi',
    description: 'KTÜ, 1955\'te kurulmuş Karadeniz bölgesinin en köklü ve büyük üniversitesidir. Orman, ziraat, mühendislik ve tıp fakülteleri ile öne çıkar. Trabzon\'un kültürel yaşamının merkezidir.',
    rating: 4.1,
  },
  {
    id: 14,
    slug: 'cukurova',
    name: 'Çukurova Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Cukurova_University_logo.png/240px-Cukurova_University_logo.png',
    city: 'Adana',
    citySlug: 'adana',
    type: 'Devlet',
    foundedYear: 1973,
    studentCount: 60000,
    website: 'https://cu.edu.tr',
    shortDescription: 'Güney\'in tarım ve tıp merkezi',
    description: 'Çukurova Üniversitesi, 1973\'te Adana\'da kurulmuş, tarım ve tıp alanlarında öne çıkan bir üniversitedir. Balcalı Kampüsü Türkiye\'nin en büyük üniversite kampüslerinden biridir.',
    rating: 4.0,
  },
  {
    id: 15,
    slug: 'mardin-artuklu',
    name: 'Mardin Artuklu Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Mardin_Artuklu_University_logo.png/240px-Mardin_Artuklu_University_logo.png',
    city: 'Mardin',
    citySlug: 'mardin',
    type: 'Devlet',
    foundedYear: 2007,
    studentCount: 20000,
    website: 'https://artuklu.edu.tr',
    shortDescription: 'Mardin\'in kültürel mirasla birleşen üniversitesi',
    description: 'Mardin Artuklu Üniversitesi, 2007\'de kurulmuş genç bir devlet üniversitesidir. Mardin\'in eşsiz kültürel dokusu içinde eğitim veren üniversite, özellikle mimari, edebiyat ve din bilimleri alanlarında öne çıkar. Süryani ve Kürt dili programları ile de benzersizdir.',
    rating: 4.2,
  },
  {
    id: 16,
    slug: 'bilkent',
    name: 'Bilkent Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Bilkent_University_logo.png/240px-Bilkent_University_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Vakıf',
    foundedYear: 1984,
    studentCount: 13000,
    website: 'https://bilkent.edu.tr',
    shortDescription: 'Türkiye\'nin ilk özel üniversitesi',
    description: 'Bilkent Üniversitesi, 1984\'te İhsan Doğramacı tarafından kurulmuş Türkiye\'nin ilk vakıf üniversitesidir. İngilizce eğitim veren üniversite, akademik kalitesi ve uluslararası tanınırlığı ile öne çıkar.',
    rating: 4.5,
  },
  {
    id: 17,
    slug: 'koc',
    name: 'Koç Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Koc_University_Logo.png/240px-Koc_University_Logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1993,
    studentCount: 7000,
    website: 'https://ku.edu.tr',
    shortDescription: 'Prestijli özel üniversite',
    description: 'Koç Üniversitesi, 1993\'te Vehbi Koç Vakfı tarafından kurulmuştur. Sarıyer\'deki modern kampüsü ile İstanbul\'un en prestijli vakıf üniversitelerinden biridir. Tıp, mühendislik ve işletme alanlarında güçlüdür.',
    rating: 4.6,
  },
  {
    id: 18,
    slug: 'sabanci',
    name: 'Sabancı Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Sabanci_University_logo.png/240px-Sabanci_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1996,
    studentCount: 4500,
    website: 'https://sabanciuniv.edu',
    shortDescription: 'Yenilikçi özel üniversite',
    description: 'Sabancı Üniversitesi, 1996\'da Sabancı Vakfı tarafından kurulmuştur. Tuzla\'daki kampüsünde disiplinlerarası eğitim yaklaşımı ve yenilikçi eğitim modeli ile tanınır.',
    rating: 4.5,
  },
  {
    id: 19,
    slug: 'ozyegin',
    name: 'Özyeğin Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Ozyegin_University_logo.png/240px-Ozyegin_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 2007,
    studentCount: 8000,
    website: 'https://ozyegin.edu.tr',
    shortDescription: 'Girişimcilik odaklı üniversite',
    description: 'Özyeğin Üniversitesi, 2007\'de Hüsnü M. Özyeğin Vakfı tarafından kurulmuştur. Çekmeköy kampüsü ile girişimcilik ve iş dünyası odaklı bir eğitim veriyor.',
    rating: 4.3,
  },
  {
    id: 20,
    slug: 'tobb-etu',
    name: 'TOBB ETÜ',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/TOBB_ETU_logo.png/240px-TOBB_ETU_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Vakıf',
    foundedYear: 2003,
    studentCount: 5000,
    website: 'https://etu.edu.tr',
    shortDescription: 'Sektörel eğitim modeli',
    description: 'TOBB Ekonomi ve Teknoloji Üniversitesi, 2003\'te TOBB tarafından kurulmuştur. Öğrencilere sektörel deneyim sağlayan Ortak Eğitim modeli ile öne çıkar.',
    rating: 4.4,
  },
  {
    id: 21,
    slug: 'bahcesehir',
    name: 'Bahçeşehir Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Bahcesehir_University_logo.png/240px-Bahcesehir_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1998,
    studentCount: 25000,
    website: 'https://bau.edu.tr',
    shortDescription: 'Uluslararası bağlantılı üniversite',
    description: 'Bahçeşehir Üniversitesi, 1998\'de kurulmuş, uluslararası ortakları ile öne çıkan bir vakıf üniversitesidir. Beşiktaş\'taki kampüsü ile İstanbul\'un kalbinde eğitim verir.',
    rating: 4.2,
  },
  {
    id: 22,
    slug: 'yeditepe',
    name: 'Yeditepe Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Yeditepe_University_logo.png/240px-Yeditepe_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1996,
    studentCount: 20000,
    website: 'https://yeditepe.edu.tr',
    shortDescription: 'Geniş kampüslü vakıf üniversitesi',
    description: 'Yeditepe Üniversitesi, 1996\'da İstanbul Eğitim ve Kültür Vakfı tarafından kurulmuştur. Kayışdağı\'ndaki geniş kampüsü ile İstanbul\'un tanınmış vakıf üniversitelerindendir.',
    rating: 4.1,
  },
  {
    id: 23,
    slug: 'kadir-has',
    name: 'Kadir Has Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Kadir_Has_University_logo.png/240px-Kadir_Has_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1997,
    studentCount: 8000,
    website: 'https://khas.edu.tr',
    shortDescription: 'Cibali\'nin tarihi kampüsü',
    description: 'Kadir Has Üniversitesi, 1997\'de kurulmuş, Cibali\'deki tarihi tütün fabrikası binasında eğitim veren özel bir üniversitedir. İletişim ve sanat alanlarında güçlüdür.',
    rating: 4.2,
  },
  {
    id: 24,
    slug: 'isik',
    name: 'Işık Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Isik_University_logo.png/240px-Isik_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1996,
    studentCount: 6000,
    website: 'https://isikun.edu.tr',
    shortDescription: 'Feyziye Mektepleri Vakfı üniversitesi',
    description: 'Işık Üniversitesi, 1996\'da Feyziye Mektepleri Vakfı tarafından kurulmuştur. Şile\'deki kampüsü ile İstanbul\'un kuzeyinde eğitim verir.',
    rating: 4.0,
  },
  {
    id: 25,
    slug: 'atilim',
    name: 'Atılım Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Atilim_University_logo.png/240px-Atilim_University_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Vakıf',
    foundedYear: 1997,
    studentCount: 12000,
    website: 'https://atilim.edu.tr',
    shortDescription: 'Ankara\'nın vakıf üniversitesi',
    description: 'Atılım Üniversitesi, 1997\'de Atılım Vakfı tarafından Ankara\'da kurulmuştur. Mühendislik ve işletme alanlarında öne çıkar.',
    rating: 4.0,
  },
]

export function getUniversite(slug: string): Universite | undefined {
  return universiteler.find(u => u.slug === slug)
}

export function getUniversitelerByCity(citySlug: string): Universite[] {
  return universiteler.filter(u => u.citySlug === citySlug)
}
