export interface Universite {
  id: number
  slug: string
  name: string
  logo: string
  city: string
  citySlug: string
  type: 'Devlet' | 'Vakıf'
  foundedYear: number
  studentCount: number
  website: string
  shortDescription: string
  description: string
  rating?: number
}

export const universiteler: Universite[] = [
  // İSTANBUL - DEVLET
  {
    id: 1,
    slug: 'bogazici-universitesi',
    name: 'Boğaziçi Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Bogazici_University_Logo.png/240px-Bogazici_University_Logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Devlet',
    foundedYear: 1863,
    studentCount: 15000,
    website: 'https://bogazici.edu.tr',
    shortDescription: 'Türkiye\'nin en prestijli üniversitelerinden biri',
    description: 'Boğaziçi Üniversitesi, 1863 yılında Robert Koleji olarak kurulmuş, Türkiye\'nin en köklü ve prestijli yükseköğretim kurumlarından biridir. İngilizce eğitim veren üniversite, akademik başarıları ve uluslararası tanınırlığı ile öne çıkar. Boğaz manzaralı kampüsü ile de meşhurdur.',
    rating: 4.8,
  },
  {
    id: 2,
    slug: 'itu',
    name: 'İstanbul Teknik Üniversitesi (İTÜ)',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Istanbul_Technical_University_logo.png/240px-Istanbul_Technical_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Devlet',
    foundedYear: 1773,
    studentCount: 39000,
    website: 'https://itu.edu.tr',
    shortDescription: 'Dünyanın en eski teknik üniversitelerinden',
    description: 'İTÜ, 1773 yılında kurulmuş dünyanın en eski teknik üniversitelerinden biridir. Mühendislik ve mimarlık alanlarında güçlü bir geleneğe sahiptir. Ayazağa ve Taşkışla kampüsleri ile İstanbul\'da 250 yılı aşkın bir tarihi vardır.',
    rating: 4.6,
  },
  {
    id: 3,
    slug: 'istanbul-universitesi',
    name: 'İstanbul Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Istanbul_University_logo.png/240px-Istanbul_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Devlet',
    foundedYear: 1453,
    studentCount: 60000,
    website: 'https://istanbul.edu.tr',
    shortDescription: 'Türkiye\'nin en eski üniversitesi',
    description: 'İstanbul Üniversitesi, 1453 yılına dayanan tarihi ile Türkiye\'nin en eski üniversitesidir. Beyazıt\'taki tarihi ana binası ile bilinen üniversite, hukuk, tıp, edebiyat ve fen bilimleri alanlarında güçlüdür.',
    rating: 4.2,
  },
  {
    id: 4,
    slug: 'marmara',
    name: 'Marmara Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Marmara_University_logo.png/240px-Marmara_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Devlet',
    foundedYear: 1883,
    studentCount: 70000,
    website: 'https://marmara.edu.tr',
    shortDescription: 'İktisadi bilimlerde güçlü köklü üniversite',
    description: 'Marmara Üniversitesi, 1883\'te kurulmuş köklü bir üniversitedir. İktisat, işletme, siyasal bilgiler ve iletişim fakülteleri ile öne çıkar. İstanbul\'un farklı yerlerinde birden fazla kampüse sahiptir.',
    rating: 4.1,
  },
  {
    id: 5,
    slug: 'yildiz-teknik',
    name: 'Yıldız Teknik Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Yildiz_Technical_University_logo.png/240px-Yildiz_Technical_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Devlet',
    foundedYear: 1911,
    studentCount: 32000,
    website: 'https://yildiz.edu.tr',
    shortDescription: 'Mühendislikte güçlü teknik üniversite',
    description: 'YTÜ, 1911\'de kurulmuş, mühendislik ve mimarlık alanlarında güçlü bir teknik üniversitedir. Yıldız ve Davutpaşa kampüsleri ile İstanbul\'da eğitim veriyor.',
    rating: 4.2,
  },
  {
    id: 6,
    slug: 'istanbul-medeniyet',
    name: 'İstanbul Medeniyet Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Istanbul_Medeniyet_University_logo.png/240px-Istanbul_Medeniyet_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Devlet',
    foundedYear: 2010,
    studentCount: 15000,
    website: 'https://medeniyet.edu.tr',
    shortDescription: 'Kadıköy\'deki genç devlet üniversitesi',
    description: 'İstanbul Medeniyet Üniversitesi, 2010\'da Kadıköy\'de kurulmuş genç bir devlet üniversitesidir. Sosyal bilimler ve tıp alanlarında öne çıkar.',
    rating: 4.0,
  },
  {
    id: 7,
    slug: 'galatasaray',
    name: 'Galatasaray Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Galatasaray_University_logo.png/240px-Galatasaray_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Devlet',
    foundedYear: 1992,
    studentCount: 3500,
    website: 'https://gsu.edu.tr',
    shortDescription: 'Fransız eğitim modelli seçkin üniversite',
    description: 'Galatasaray Üniversitesi, 1992\'de kurulmuş, Fransızca eğitim veren prestijli bir devlet üniversitesidir. Ortaköy\'deki Boğaz manzaralı kampüsü ile bilinir.',
    rating: 4.5,
  },
  {
    id: 8,
    slug: 'mimar-sinan',
    name: 'Mimar Sinan Güzel Sanatlar Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Mimar_Sinan_Fine_Arts_University_logo.png/240px-Mimar_Sinan_Fine_Arts_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Devlet',
    foundedYear: 1882,
    studentCount: 7000,
    website: 'https://msgsu.edu.tr',
    shortDescription: 'Sanat ve mimaride öncü üniversite',
    description: 'Mimar Sinan, 1882\'de "Sanayi-i Nefise Mektebi" olarak kurulmuş, Türkiye\'nin ilk güzel sanatlar akademisidir. Fındıklı\'daki tarihi binasında eğitim verir.',
    rating: 4.3,
  },

  // İSTANBUL - VAKIF
  {
    id: 9,
    slug: 'koc',
    name: 'Koç Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Koc_University_Logo.png/240px-Koc_University_Logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1993,
    studentCount: 7000,
    website: 'https://ku.edu.tr',
    shortDescription: 'Prestijli özel üniversite',
    description: 'Koç Üniversitesi, 1993\'te Vehbi Koç Vakfı tarafından kurulmuştur. Sarıyer\'deki modern kampüsü ile İstanbul\'un en prestijli vakıf üniversitelerinden biridir.',
    rating: 4.6,
  },
  {
    id: 10,
    slug: 'sabanci',
    name: 'Sabancı Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Sabanci_University_logo.png/240px-Sabanci_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1996,
    studentCount: 4500,
    website: 'https://sabanciuniv.edu',
    shortDescription: 'Yenilikçi özel üniversite',
    description: 'Sabancı Üniversitesi, 1996\'da Sabancı Vakfı tarafından kurulmuştur. Tuzla\'daki kampüsünde disiplinlerarası eğitim yaklaşımı ile tanınır.',
    rating: 4.5,
  },
  {
    id: 11,
    slug: 'ozyegin',
    name: 'Özyeğin Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Ozyegin_University_logo.png/240px-Ozyegin_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 2007,
    studentCount: 8000,
    website: 'https://ozyegin.edu.tr',
    shortDescription: 'Girişimcilik odaklı üniversite',
    description: 'Özyeğin Üniversitesi, 2007\'de Hüsnü M. Özyeğin Vakfı tarafından kurulmuştur. Çekmeköy kampüsü ile girişimcilik odaklı eğitim veriyor.',
    rating: 4.3,
  },
  {
    id: 12,
    slug: 'bahcesehir',
    name: 'Bahçeşehir Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Bahcesehir_University_logo.png/240px-Bahcesehir_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1998,
    studentCount: 25000,
    website: 'https://bau.edu.tr',
    shortDescription: 'Uluslararası bağlantılı üniversite',
    description: 'Bahçeşehir Üniversitesi, 1998\'de kurulmuş, uluslararası ortakları ile öne çıkan bir vakıf üniversitesidir. Beşiktaş\'taki kampüsü ile İstanbul\'un kalbinde eğitim verir.',
    rating: 4.2,
  },
  {
    id: 13,
    slug: 'yeditepe',
    name: 'Yeditepe Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Yeditepe_University_logo.png/240px-Yeditepe_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1996,
    studentCount: 20000,
    website: 'https://yeditepe.edu.tr',
    shortDescription: 'Geniş kampüslü vakıf üniversitesi',
    description: 'Yeditepe Üniversitesi, 1996\'da kurulmuştur. Kayışdağı\'ndaki geniş kampüsü ile İstanbul\'un tanınmış vakıf üniversitelerindendir.',
    rating: 4.1,
  },
  {
    id: 14,
    slug: 'kadir-has',
    name: 'Kadir Has Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Kadir_Has_University_logo.png/240px-Kadir_Has_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1997,
    studentCount: 8000,
    website: 'https://khas.edu.tr',
    shortDescription: 'Cibali\'nin tarihi kampüsü',
    description: 'Kadir Has Üniversitesi, 1997\'de kurulmuş, Cibali\'deki tarihi tütün fabrikası binasında eğitim veren özel bir üniversitedir.',
    rating: 4.2,
  },
  {
    id: 15,
    slug: 'isik',
    name: 'Işık Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Isik_University_logo.png/240px-Isik_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1996,
    studentCount: 6000,
    website: 'https://isikun.edu.tr',
    shortDescription: 'Feyziye Mektepleri Vakfı üniversitesi',
    description: 'Işık Üniversitesi, 1996\'da Feyziye Mektepleri Vakfı tarafından kurulmuştur. Şile\'deki kampüsü ile İstanbul\'un kuzeyinde eğitim verir.',
    rating: 4.0,
  },
  {
    id: 16,
    slug: 'medipol',
    name: 'İstanbul Medipol Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Medipol_Universitesi_logo.png/240px-Medipol_Universitesi_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 2009,
    studentCount: 30000,
    website: 'https://medipol.edu.tr',
    shortDescription: 'Sağlık alanında öne çıkan üniversite',
    description: 'İstanbul Medipol Üniversitesi, 2009\'da kurulmuş, özellikle tıp ve sağlık bilimleri alanında güçlü bir vakıf üniversitesidir.',
    rating: 4.1,
  },
  {
    id: 17,
    slug: 'okan',
    name: 'Okan Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Okan_University_logo.png/240px-Okan_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1999,
    studentCount: 15000,
    website: 'https://okan.edu.tr',
    shortDescription: 'Tuzla\'daki modern vakıf üniversitesi',
    description: 'Okan Üniversitesi, 1999\'da kurulmuştur. Tuzla\'daki kampüsü ile modern bir eğitim ortamı sunar.',
    rating: 4.0,
  },
  {
    id: 18,
    slug: 'maltepe',
    name: 'Maltepe Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Maltepe_University_logo.png/240px-Maltepe_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 1997,
    studentCount: 12000,
    website: 'https://maltepe.edu.tr',
    shortDescription: 'Marmara denizi manzaralı üniversite',
    description: 'Maltepe Üniversitesi, 1997\'de kurulmuş, deniz manzaralı kampüsü ile İstanbul\'un Anadolu yakasında yer alır.',
    rating: 3.9,
  },
  {
    id: 19,
    slug: 'aydin',
    name: 'İstanbul Aydın Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Istanbul_Aydin_University_logo.png/240px-Istanbul_Aydin_University_logo.png',
    city: 'İstanbul',
    citySlug: 'istanbul',
    type: 'Vakıf',
    foundedYear: 2007,
    studentCount: 40000,
    website: 'https://aydin.edu.tr',
    shortDescription: 'Türkiye\'nin en büyük vakıf üniversitelerinden',
    description: 'İstanbul Aydın Üniversitesi, 2007\'de kurulmuş, öğrenci sayısı bakımından Türkiye\'nin en büyük vakıf üniversitelerinden biridir.',
    rating: 3.8,
  },

  // ANKARA - DEVLET
  {
    id: 20,
    slug: 'odtu',
    name: 'Orta Doğu Teknik Üniversitesi (ODTÜ)',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/METU_Logo.png/240px-METU_Logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Devlet',
    foundedYear: 1956,
    studentCount: 27000,
    website: 'https://metu.edu.tr',
    shortDescription: 'Mühendislik ve teknolojide öncü üniversite',
    description: 'ODTÜ, 1956 yılında kurulmuş ve özellikle mühendislik alanında Türkiye\'nin en güçlü üniversitelerinden biridir. İngilizce eğitim veren ODTÜ, geniş kampüsü ile tanınır.',
    rating: 4.7,
  },
  {
    id: 21,
    slug: 'hacettepe',
    name: 'Hacettepe Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Hacettepe_University_logo.png/240px-Hacettepe_University_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Devlet',
    foundedYear: 1967,
    studentCount: 45000,
    website: 'https://hacettepe.edu.tr',
    shortDescription: 'Tıp fakültesiyle öne çıkan köklü üniversite',
    description: 'Hacettepe Üniversitesi, 1967 yılında kurulmuş olup özellikle tıp, sağlık bilimleri ve mühendislik alanlarında öne çıkar. Beytepe ve Sıhhiye kampüsleri ile Ankara\'nın en büyük üniversitelerinden biridir.',
    rating: 4.4,
  },
  {
    id: 22,
    slug: 'ankara-universitesi',
    name: 'Ankara Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Ankara_University_logo.png/240px-Ankara_University_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Devlet',
    foundedYear: 1946,
    studentCount: 65000,
    website: 'https://ankara.edu.tr',
    shortDescription: 'Cumhuriyetin ilk üniversitesi',
    description: 'Ankara Üniversitesi, 1946 yılında kurulmuş Cumhuriyet döneminin ilk üniversitesidir. Hukuk, siyasal bilgiler, veterinerlik ve ziraat fakülteleri ile tanınır.',
    rating: 4.3,
  },
  {
    id: 23,
    slug: 'gazi',
    name: 'Gazi Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Gazi_University_logo.png/240px-Gazi_University_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Devlet',
    foundedYear: 1926,
    studentCount: 70000,
    website: 'https://gazi.edu.tr',
    shortDescription: 'Öğretmen yetiştirmede öncü',
    description: 'Gazi Üniversitesi, 1926\'da Atatürk tarafından "Gazi Eğitim Enstitüsü" olarak kurulmuştur. Türkiye\'nin öğretmen yetiştirmede en köklü kurumlarından biridir.',
    rating: 4.1,
  },
  {
    id: 24,
    slug: 'ytu-teknik',
    name: 'Ankara Yıldırım Beyazıt Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/AYBU_logo.png/240px-AYBU_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Devlet',
    foundedYear: 2010,
    studentCount: 20000,
    website: 'https://aybu.edu.tr',
    shortDescription: 'Genç ve dinamik devlet üniversitesi',
    description: 'AYBÜ, 2010\'da Ankara\'da kurulmuş genç bir devlet üniversitesidir.',
    rating: 4.0,
  },
  {
    id: 25,
    slug: 'hacibayram',
    name: 'Ankara Hacı Bayram Veli Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/HBV_logo.png/240px-HBV_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Devlet',
    foundedYear: 2018,
    studentCount: 40000,
    website: 'https://hacibayram.edu.tr',
    shortDescription: 'İletişim ve sanat odaklı üniversite',
    description: 'HBV Üniversitesi, 2018\'de Gazi Üniversitesi\'nden ayrılarak kurulmuştur. İletişim ve güzel sanatlar alanlarında güçlüdür.',
    rating: 3.9,
  },

  // ANKARA - VAKIF
  {
    id: 26,
    slug: 'bilkent',
    name: 'Bilkent Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Bilkent_University_logo.png/240px-Bilkent_University_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Vakıf',
    foundedYear: 1984,
    studentCount: 13000,
    website: 'https://bilkent.edu.tr',
    shortDescription: 'Türkiye\'nin ilk özel üniversitesi',
    description: 'Bilkent Üniversitesi, 1984\'te İhsan Doğramacı tarafından kurulmuş Türkiye\'nin ilk vakıf üniversitesidir. İngilizce eğitim veren üniversite akademik kalitesi ile öne çıkar.',
    rating: 4.5,
  },
  {
    id: 27,
    slug: 'tobb-etu',
    name: 'TOBB ETÜ',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/TOBB_ETU_logo.png/240px-TOBB_ETU_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Vakıf',
    foundedYear: 2003,
    studentCount: 5000,
    website: 'https://etu.edu.tr',
    shortDescription: 'Sektörel eğitim modeli',
    description: 'TOBB Ekonomi ve Teknoloji Üniversitesi, 2003\'te TOBB tarafından kurulmuştur. Ortak Eğitim modeli ile öne çıkar.',
    rating: 4.4,
  },
  {
    id: 28,
    slug: 'atilim',
    name: 'Atılım Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Atilim_University_logo.png/240px-Atilim_University_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Vakıf',
    foundedYear: 1997,
    studentCount: 12000,
    website: 'https://atilim.edu.tr',
    shortDescription: 'Ankara\'nın vakıf üniversitesi',
    description: 'Atılım Üniversitesi, 1997\'de Ankara\'da kurulmuştur. Mühendislik ve işletme alanlarında öne çıkar.',
    rating: 4.0,
  },
  {
    id: 29,
    slug: 'baskent',
    name: 'Başkent Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Baskent_University_logo.png/240px-Baskent_University_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Vakıf',
    foundedYear: 1994,
    studentCount: 13000,
    website: 'https://baskent.edu.tr',
    shortDescription: 'Sağlık alanında güçlü vakıf üniversitesi',
    description: 'Başkent Üniversitesi, 1994\'te kurulmuş, özellikle tıp ve sağlık bilimleri alanında öne çıkan bir vakıf üniversitesidir.',
    rating: 4.1,
  },
  {
    id: 30,
    slug: 'cankaya',
    name: 'Çankaya Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Cankaya_University_logo.png/240px-Cankaya_University_logo.png',
    city: 'Ankara',
    citySlug: 'ankara',
    type: 'Vakıf',
    foundedYear: 1997,
    studentCount: 8000,
    website: 'https://cankaya.edu.tr',
    shortDescription: 'Hukuk ve mühendislikte güçlü üniversite',
    description: 'Çankaya Üniversitesi, 1997\'de Sıtkı Alp Eğitim Vakfı tarafından kurulmuştur.',
    rating: 4.0,
  },

  // İZMİR
  {
    id: 31,
    slug: 'ege',
    name: 'Ege Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Ege_University_logo.png/240px-Ege_University_logo.png',
    city: 'İzmir',
    citySlug: 'izmir',
    type: 'Devlet',
    foundedYear: 1955,
    studentCount: 55000,
    website: 'https://ege.edu.tr',
    shortDescription: 'İzmir\'in en köklü üniversitesi',
    description: 'Ege Üniversitesi, 1955\'te İzmir\'de kurulmuş büyük bir devlet üniversitesidir. Tıp, ziraat, mühendislik ve fen bilimleri alanlarında öne çıkar.',
    rating: 4.3,
  },
  {
    id: 32,
    slug: 'dokuz-eylul',
    name: 'Dokuz Eylül Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Dokuz_Eylul_University_logo.png/240px-Dokuz_Eylul_University_logo.png',
    city: 'İzmir',
    citySlug: 'izmir',
    type: 'Devlet',
    foundedYear: 1982,
    studentCount: 65000,
    website: 'https://deu.edu.tr',
    shortDescription: 'İzmir\'in büyük devlet üniversitesi',
    description: 'Dokuz Eylül Üniversitesi, 1982\'de kurulmuş, İzmir\'in en büyük üniversitelerinden biridir.',
    rating: 4.2,
  },
  {
    id: 33,
    slug: 'iyte',
    name: 'İzmir Yüksek Teknoloji Enstitüsü',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/IZTECH_logo.png/240px-IZTECH_logo.png',
    city: 'İzmir',
    citySlug: 'izmir',
    type: 'Devlet',
    foundedYear: 1992,
    studentCount: 4500,
    website: 'https://iyte.edu.tr',
    shortDescription: 'Teknoloji odaklı devlet üniversitesi',
    description: 'İYTE, 1992\'de kurulmuş, mühendislik ve fen bilimlerinde uzmanlaşmış bir üniversitedir. Urla\'daki kampüsü ile bilinir.',
    rating: 4.4,
  },
  {
    id: 34,
    slug: 'katip-celebi',
    name: 'İzmir Kâtip Çelebi Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/IKCU_logo.png/240px-IKCU_logo.png',
    city: 'İzmir',
    citySlug: 'izmir',
    type: 'Devlet',
    foundedYear: 2010,
    studentCount: 20000,
    website: 'https://ikcu.edu.tr',
    shortDescription: 'Genç devlet üniversitesi',
    description: 'İKÇÜ, 2010\'da kurulmuş İzmir\'in genç devlet üniversitelerinden biridir.',
    rating: 4.0,
  },
  {
    id: 35,
    slug: 'yasar',
    name: 'Yaşar Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Yasar_University_logo.png/240px-Yasar_University_logo.png',
    city: 'İzmir',
    citySlug: 'izmir',
    type: 'Vakıf',
    foundedYear: 2001,
    studentCount: 7000,
    website: 'https://yasar.edu.tr',
    shortDescription: 'İzmir\'in vakıf üniversitesi',
    description: 'Yaşar Üniversitesi, 2001\'de Selçuk Yaşar Vakfı tarafından kurulmuştur.',
    rating: 4.1,
  },
  {
    id: 36,
    slug: 'yasar-ekonomi',
    name: 'İzmir Ekonomi Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/IEU_logo.png/240px-IEU_logo.png',
    city: 'İzmir',
    citySlug: 'izmir',
    type: 'Vakıf',
    foundedYear: 2001,
    studentCount: 9000,
    website: 'https://ieu.edu.tr',
    shortDescription: 'İş dünyası odaklı vakıf üniversitesi',
    description: 'İzmir Ekonomi Üniversitesi, 2001\'de İZTO tarafından kurulmuş özel bir üniversitedir.',
    rating: 4.2,
  },

  // ESKİŞEHİR
  {
    id: 37,
    slug: 'anadolu',
    name: 'Anadolu Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Anadolu_University_logo.png/240px-Anadolu_University_logo.png',
    city: 'Eskişehir',
    citySlug: 'eskisehir',
    type: 'Devlet',
    foundedYear: 1958,
    studentCount: 1200000,
    website: 'https://anadolu.edu.tr',
    shortDescription: 'Türkiye\'nin en büyük açık öğretim üniversitesi',
    description: 'Anadolu Üniversitesi, 1958\'de Eskişehir\'de kurulmuş olup Açık Öğretim Fakültesi ile Türkiye\'nin en büyük üniversitesidir.',
    rating: 4.0,
  },
  {
    id: 38,
    slug: 'osmangazi',
    name: 'Eskişehir Osmangazi Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Osmangazi_University_logo.png/240px-Osmangazi_University_logo.png',
    city: 'Eskişehir',
    citySlug: 'eskisehir',
    type: 'Devlet',
    foundedYear: 1993,
    studentCount: 25000,
    website: 'https://ogu.edu.tr',
    shortDescription: 'Eskişehir\'in ikinci büyük üniversitesi',
    description: 'ESOGÜ, 1993\'te kurulmuş, tıp ve mühendislik alanlarında güçlü bir devlet üniversitesidir.',
    rating: 4.0,
  },

  // TRABZON
  {
    id: 39,
    slug: 'ktu',
    name: 'Karadeniz Teknik Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/KTU_logo.png/240px-KTU_logo.png',
    city: 'Trabzon',
    citySlug: 'trabzon',
    type: 'Devlet',
    foundedYear: 1955,
    studentCount: 60000,
    website: 'https://ktu.edu.tr',
    shortDescription: 'Karadeniz\'in köklü üniversitesi',
    description: 'KTÜ, 1955\'te kurulmuş Karadeniz bölgesinin en köklü ve büyük üniversitesidir. Orman, ziraat, mühendislik ve tıp fakülteleri ile öne çıkar.',
    rating: 4.1,
  },
  {
    id: 40,
    slug: 'avrasya',
    name: 'Avrasya Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Avrasya_University_logo.png/240px-Avrasya_University_logo.png',
    city: 'Trabzon',
    citySlug: 'trabzon',
    type: 'Vakıf',
    foundedYear: 2010,
    studentCount: 3000,
    website: 'https://avrasya.edu.tr',
    shortDescription: 'Trabzon\'un vakıf üniversitesi',
    description: 'Avrasya Üniversitesi, 2010\'da Trabzon\'da kurulmuş bir vakıf üniversitesidir.',
    rating: 3.8,
  },

  // ADANA
  {
    id: 41,
    slug: 'cukurova',
    name: 'Çukurova Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Cukurova_University_logo.png/240px-Cukurova_University_logo.png',
    city: 'Adana',
    citySlug: 'adana',
    type: 'Devlet',
    foundedYear: 1973,
    studentCount: 60000,
    website: 'https://cu.edu.tr',
    shortDescription: 'Güney\'in tarım ve tıp merkezi',
    description: 'Çukurova Üniversitesi, 1973\'te Adana\'da kurulmuş, tarım ve tıp alanlarında öne çıkan bir üniversitedir. Balcalı Kampüsü Türkiye\'nin en büyük kampüslerinden biridir.',
    rating: 4.0,
  },
  {
    id: 42,
    slug: 'adana-alparslan',
    name: 'Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/ATU_logo.png/240px-ATU_logo.png',
    city: 'Adana',
    citySlug: 'adana',
    type: 'Devlet',
    foundedYear: 2011,
    studentCount: 6000,
    website: 'https://atu.edu.tr',
    shortDescription: 'Bilim ve teknoloji üniversitesi',
    description: 'Adana Alparslan Türkeş, 2011\'de kurulmuş, mühendislik ve teknoloji alanında uzmanlaşmış bir üniversitedir.',
    rating: 3.9,
  },

  // MARDİN
  {
    id: 43,
    slug: 'mardin-artuklu',
    name: 'Mardin Artuklu Üniversitesi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Mardin_Artuklu_University_logo.png/240px-Mardin_Artuklu_University_logo.png',
    city: 'Mardin',
    citySlug: 'mardin',
    type: 'Devlet',
    foundedYear: 2007,
    studentCount: 20000,
    website: 'https://artuklu.edu.tr',
    shortDescription: 'Mardin\'in kültürel mirasla birleşen üniversitesi',
    description: 'Mardin Artuklu Üniversitesi, 2007\'de kurulmuş genç bir devlet üniversitesidir. Mardin\'in eşsiz kültürel dokusu içinde eğitim veren üniversite, özellikle mimari, edebiyat ve din bilimleri alanlarında öne çıkar.',
    rating: 4.2,
  },
]

export function getUniversite(slug: string): Universite | undefined {
  return universiteler.find(u => u.slug === slug)
}

export function getUniversitelerByCity(citySlug: string): Universite[] {
  return universiteler.filter(u => u.citySlug === citySlug)
}
